### PR TITLE
[WIP][95] Trying Spark 2.0 tests

### PR DESCRIPTION
**Pull request by thunterdb**

### CODE REVIEW

**Comment by felixcheung** [comment]
```
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalatest#scalatest_2.11;2.0: not found
[error] Total time: 9 s, completed Jul 27, 2016 12:00:00 AM
```

**Comment by thunterdb** [comment]
@felixcheung I will not be able to work on it until late next week. Please feel free to take over this PR if you have some time.

**Comment by felixcheung** [comment]
ok i will try to take a look

**Comment by felixcheung** [comment]
in #99

**Comment by thunterdb** [comment]
Closing this PR, it has been fixed by #100

**Pull request closed without merging**
