### PR TITLE
Support Spark 1.6.1

### PR DESCRIPTION
**Pull request by felixcheung**

### CODE REVIEW

**Comment by felixcheung** [comment]
That's odd, it looks like the download is bad:
```
Spark build URL = http://d3kbcqa49mib13.cloudfront.net/spark-1.6.1-bin-hadoop2.6.tgz
Downloading file...
/usr/bin/curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 20  239M   20 48.5M    0     0  57.1M      0  0:00:04 --:--:--  0:00:04 57.9M
 49  239M   49  117M    0     0  62.8M      0  0:00:03  0:00:01  0:00:02 63.1M
 87  239M   87  208M    0     0  72.6M      0  0:00:03  0:00:02  0:00:01 72.8M
100  239M  100  239M    0     0  75.4M      0  0:00:03  0:00:03 --:--:-- 75.7M
Content of directory:
-rw-rw-r--  1 travis travis 280907391 Mar  9 00:52 /home/travis/.cache/spark-versions/spark-1.5.2-bin-hadoop2.6.tgz
-rw-rw-r--  1 travis travis 289160984 Mar 16 21:32 /home/travis/.cache/spark-versions/spark-1.6.0-bin-hadoop2.6.tgz
-rw-rw-r--  1 travis travis 250923653 Apr  2 17:52 /home/travis/.cache/spark-versions/spark-1.6.1-bin-hadoop2.6.tgz

/home/travis/.cache/spark-versions/spark-1.5.2-bin-hadoop2.6:
total 1036
drwxr-xr-x 12 travis travis   4096 Nov  3 18:05 .
drwxrwxr-x  4 travis travis   4096 Apr  2 17:52 ..
drwxr-xr-x  2 travis travis   4096 Nov  3 18:05 bin
-rw-r--r--  1 travis travis 975887 Nov  3 18:05 CHANGES.txt
drwxr-xr-x  2 travis travis   4096 Nov  3 18:05 conf
drwxr-xr-x  3 travis travis     18 Nov  3 18:05 data
drwxr-xr-x  3 travis travis     75 Nov  3 18:05 ec2
drwxr-xr-x  3 travis travis     16 Nov  3 18:05 examples
drwxr-xr-x  2 travis travis   4096 Nov  3 18:05 lib
-rw-r--r--  1 travis travis  17356 Nov  3 18:05 LICENSE
drwxr-xr-x  2 travis travis   4096 Nov  3 18:05 licenses
-rw-r--r--  1 travis travis  23158 Nov  3 18:05 NOTICE
drwxr-xr-x  6 travis travis    112 Nov  3 18:05 python
drwxr-xr-x  3 travis travis     16 Nov  3 18:05 R
-rw-r--r--  1 travis travis   3593 Nov  3 18:05 README.md
-rw-r--r--  1 travis travis    120 Nov  3 18:05 RELEASE
drwxr-xr-x  2 travis travis   4096 Nov  3 18:05 sbin

/home/travis/.cache/spark-versions/spark-1.6.0-bin-hadoop2.6:
total 1364
drwxr-xr-x 12 travis travis    4096 Dec 22 02:22 .
drwxrwxr-x  4 travis travis    4096 Apr  2 17:52 ..
drwxr-xr-x  2 travis travis    4096 Dec 22 02:22 bin
-rw-r--r--  1 travis travis 1312258 Dec 22 02:22 CHANGES.txt
drwxr-xr-x  2 travis travis    4096 Dec 22 02:22 conf
drwxr-xr-x  3 travis travis      18 Dec 22 02:22 data
drwxr-xr-x  3 travis travis      75 Dec 22 02:22 ec2
drwxr-xr-x  3 travis travis      16 Dec 22 02:22 examples
drwxr-xr-x  2 travis travis    4096 Dec 22 02:22 lib
-rw-r--r--  1 travis travis   17352 Dec 22 02:22 LICENSE
drwxr-xr-x  2 travis travis    4096 Dec 22 02:22 licenses
-rw-r--r--  1 travis travis   23529 Dec 22 02:22 NOTICE
drwxr-xr-x  6 travis travis     112 Dec 22 02:22 python
drwxr-xr-x  3 travis travis      16 Dec 22 02:22 R
-rw-r--r--  1 travis travis    3359 Dec 22 02:22 README.md
-rw-r--r--  1 travis travis     120 Dec 22 02:22 RELEASE
drwxr-xr-x  2 travis travis    4096 Dec 22 02:22 sbin

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by jkbradley** [comment]
this LGTM.  I assume the failure was spurious.  testing again

**Comment by jkbradley** [comment]
OK not spurious.  I'm told it's being fixed.

**Comment by jkbradley** [comment]
Now merging!  Thanks for the patch

**Pull request merged**
