### PR TITLE
Change inequality operator

### PR DESCRIPTION
**Pull request by ntrinquier**
`!==` is deprecated (in favor of `=!=`).

### CODE REVIEW

**Comment by felixcheung** [comment]
cool, thx. it looks like tests are failing for unrelated reasons

**Comment by ntrinquier** [comment]
@felixcheung I triggered the CI again to try to have the tests pass, no luck.

**Comment by felixcheung** [comment]
try a few more times?

```
-rw-rw-r-- 1 travis travis  376 Mar 21 10:59 spark-2.3.2-bin-hadoop2.7.tgz
+tar -zxf spark-2.3.2-bin-hadoop2.7.tgz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "./bin/download_travis_dependencies.sh" failed and exited with 2 during .

```

376 bytes look like bad download.

**Comment by ntrinquier** [comment]
@felixcheung looks like 2.3.2 is not in the mirrors anymore? at least according to https://www.apache.org/dyn/closer.lua?path=spark/spark-2.3.2/spark-2.3.2-bin-hadoop2.7.tgz

**Comment by felixcheung** [comment]
After 2.3.3 is released, 2.3.2 is taken out

________________________________

**Comment by ntrinquier** [comment]
@felixcheung I updated the CI to use 2.3.3 - checks have passed :)

**Comment by ntrinquier** [comment]
@felixcheung do you think it's good to merge?

**Pull request closed without merging**
