### PR TITLE
Moves all the public exceptions to the same file

### PR DESCRIPTION
**Pull request by thunterdb**
cc @mengxr

### CODE REVIEW

**Comment by mengxr** [comment]
Travis is not happy:)

**Comment by jkbradley** [comment]
Why are we doing cleanups like this if they don't change the public API??

**Comment by thunterdb** [comment]
The exceptions change the API (as seen in the failing test...). I also removed a block of commented out code in the process.

**Comment by mengxr** [comment]
LGTM

**Pull request merged**
