### PR TITLE
[157] Updates for 0.4.0 release

### PR DESCRIPTION
**Pull request by jkbradley**
Minor updates to docs

### CODE REVIEW

**Comment by jkbradley** [comment]
CC @thunterdb @felixcheung Did I miss anything?

Tests ran locally for (spark 2.0, 2.1) x (scala 2.10, 2.11)
I'm also testing the locally published packages.

**Comment by jkbradley** [comment]
Got a LGTM from @thunterdb offline.  Merging now.

**Comment by thunterdb** [comment]
LGTM

**Comment by felixcheung** [comment]
hooray for rolling 0.4.

comments:
- doesn't this https://github.com/jkbradley/graphframes/blob/749028eb1bdf7f3f491a12b369e4bb639c6ef477/build.sbt#L26 need to be updated?
- and https://github.com/graphframes/graphframes/blob/master/docs/_config.yml#L17

**Comment by jkbradley** [comment]
So I did update those when building the project, but I didn't want to make the master branch a non-snapshot.  Really, we should start cutting actual release branches, rather than just using tags.  Let's do that for the next release.

**Pull request merged**
