### PR TITLE
Remove backported pagerank algorithm

### PR DESCRIPTION
**Pull request by aray**
Since GraphFrames 0.3.0 removed support for Spark 1.4 and 1.5, this backport is no longer needed.

### CODE REVIEW

**Comment by felixcheung** [comment]
that's great - could you check if it works with Spark 2.1. I tried looking into this earlier and found a lot of non-trivial changes while working on #153

**Comment by aray** [comment]
I merged your 2.1 branch and verified all unit tests pass. Per `git diff v2.0.0..v2.1.0 -- /Users/andrew/spark/graphx/src/main/scala/org/apache/spark/graphx/lib/PageRank.scala` the only non trivial changes were in the addition of a new parallel personalized pagerank algorithm that is a completely separate method than what we use.

**Comment by thunterdb** [comment]
Thank you @aray. I restarted the build to check against the latest master.

**Comment by thunterdb** [comment]
Merging.

**Pull request merged**
