### PR TITLE
Update sbt to 0.13.17

### PR DESCRIPTION
**Pull request by denisgarci**
Update sbt to latest 0.13.x version. Tested locally running test and `make`.

### CODE REVIEW

**Comment by felixcheung** [comment]
can you check the test/check failure?

**Comment by denisgarci** [comment]
The error looks to come from `download_travis_dependencies.sh`:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "./bin/download_travis_dependencies.sh" failed and exited with 2 during
```
Looking at the script I don't see anything related to sbt. Any idea what might cause that error?

**Comment by felixcheung** [comment]
it might be because of spark 2.3.1, 2.2.2, 2.1.2 releases. try changing to the latest release versions here https://github.com/graphframes/graphframes/blob/master/.travis.yml#L16

**Comment by denisgarci** [comment]
@felixcheung Thanks it worked! Should I also change the Spark version in the `build.sbt` and `Makefile`?

**Comment by felixcheung** [comment]
great, yes, but perhaps you can do all the release/version changes in a separate pull request? you can ping me there and I'll merge that first. it's earlier to track than inside a sbt PR.

**Comment by felixcheung** [comment]
thx, merged that one, could you rebase?

**Comment by felixcheung** [comment]
thx

**Pull request merged**
